
x-app-base: &app-base
  image: ""


services:
  # Serviço do PostgreSQL
  pg.db.srv: &dfdfd
    ports:
      - "${POSTGRES_PORT:-}:5432"

  # Serviço do MongoDB
  mg.db.srv:
    ports:
      - "${MONGO_PORT:-}:27017"

  # Serviço de Administração PostgreSQL (API)
  admin.internal.srv:
    ports:
      - ${ADMIN_PORT:-4000}:4000


  # Serviço P2M (PostgreSQL para MongoDB)
  p2m.internal.srv:
    ports:
      - ${P2M_PORT:-5000}:5000