services:
  # Serviço do PostgreSQL
  pg.db.srv:
    image: zootakuxy/postgrade-pg
    container_name: ${SERVICE}-postgres
    hostname: pg.db.${DOMAIN}
    env_file:
      - ${POSTGRES_ENVFILE:-ignore}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-storage:/var/lib/postgresql/data
      - postgrade-storage:/etc/postgrade
    networks:
      - domain
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: on-failure
    deploy:
      resources:
        limits:
          memory: 2g
          cpus: 3.0

  # Serviço do MongoDB
  mg.db.srv:
    image: mongo:latest
    container_name: ${SERVICE}-mongo
    hostname: mg.db.${DOMAIN}
    env_file:
      - ${MONGDB_ENVFILE:-ignore}

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    volumes:
      - mongo-storage:/data/db
      - postgrade-storage:/etc/postgrade
    networks:
      - domain
    ports:
      - "${MONGO_PORT}:27017"
    restart: on-failure
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: 1.0

  # Serviço de Administração PostgreSQL (API)
  admin.internal.srv:
    container_name: ${SERVICE}-admin
    hostname: admin.internal.${DOMAIN}
    image: zootakuxy/postgrade-admin
    env_file:
      - ${ADMIN_ENVFILE:-ignore}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgrade-storage:/etc/postgrade
      - postgres-storage:/var/lib/postgresql/data
    networks:
      - domain
    ports:
      - "${ADMIN_PORT}:4000"
    depends_on:
      - pg.db.srv
    restart: on-failure
    deploy:
      resources:
        limits:
          memory: 512m
          cpus: 0.5

  # Serviço P2M (PostgreSQL para MongoDB)
  p2m.internal.srv:
    container_name: ${SERVICE}-p2m
    hostname: p2m.internal.${DOMAIN}
    image: zootakuxy/postgrade-p2m
    env_file:
      - ${P2M_ENVFILE:-ignore}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      MONGO_URI: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo:27017
    networks:
      - domain
    depends_on:
      - pg.db.srv
      - mg.db.srv
    restart: on-failure
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: 2.0

volumes:
  postgres-storage:
    name: ${SERVICE}-postgres-storage
  mongo-storage:
    name: ${SERVICE}-mongo-storage
  postgrade-storage:
    name: ${SERVICE}-postgrade-storage

networks:
  domain:
    driver: bridge
    name: ${DOMAIN}
